## Step 0  Import Libraries

In [1]:
import pandas as pd
import numpy as np
import glob
import os
print('pandas:', pd.__version__)

pandas: 3.0.2

## Step 1 — Combine All CSVs into One DataFrame

In [2]:
all_files = glob.glob('dataset/*.csv')
print(f'Found {len(all_files)} CSV files\n')

dfs = []
for file in all_files:
    try:
        temp = pd.read_csv(file, low_memory=False)
        temp['category'] = os.path.splitext(os.path.basename(file))[0]  # filename as category
        dfs.append(temp)
        print(f'  Loaded: {os.path.basename(file):40s} → {len(temp)} rows')
    except Exception as e:
        print(f'  Skipped {file}: {e}')

df = pd.concat(dfs, ignore_index=True)
print(f'\n Combined shape: {df.shape[0]:,} rows × {df.shape[1]} columns')

# Save combined raw file
df.to_csv('dataset/Combined_dataset.csv', index=False)
print(' Saved: dataset/Combined_dataset.csv')

Found 99 CSV files

  Loaded: backpacks.csv                            → 4 rows
  Loaded: bath-robe.csv                            → 1 rows
  Loaded: bath-towels.csv                          → 1 rows
  Loaded: bathroom-accessories.csv                 → 1 rows
  Loaded: bedsheets.csv                            → 11 rows
  Loaded: belts.csv                                → 1 rows
  Loaded: bodysuit.csv                             → 2 rows
  Loaded: boots.csv                                → 2 rows
  Loaded: boxers.csv                               → 1 rows
  Loaded: bra.csv                                  → 13 rows
  Loaded: bracelet.csv                             → 4 rows
  Loaded: briefs.csv                               → 12 rows
  Loaded: camisoles.csv                            → 2 rows
  Loaded: candle-holders.csv                       → 1 rows
  Loaded: caps.csv                                 → 2 rows
  Loaded: casual-shoes.csv                         → 23 rows
  Loaded: chair-cover.csv                          → 1 rows
  Loaded: clothing-set.csv                         → 2 rows
  Loaded: clutches.csv                             → 1 rows
  Loaded: co-ords.csv                              → 1 rows
  Loaded: Combined_dataset.csv                     → 2000 rows
  Loaded: Combined_dataset_cleaned.csv             → 2000 rows
  Loaded: curtains-and-sheers.csv                  → 2 rows
  Loaded: cutlery.csv                              → 1 rows
  Loaded: dinnerware.csv                           → 1 rows
  Loaded: dresses.csv                              → 100 rows
  Loaded: duffel-bag.csv                           → 2 rows
  Loaded: dungarees.csv                            → 1 rows
  Loaded: dupatta.csv                              → 11 rows
  Loaded: earrings.csv                             → 34 rows
  Loaded: ethnic-dresses.csv                       → 20 rows
  Loaded: face-moisturisers.csv                    → 2 rows
  Loaded: face-wash-and-cleanser.csv               → 1 rows
  Loaded: flats.csv                                → 12 rows
  Loaded: flip-flops.csv                           → 15 rows
  Loaded: floor-mats--dhurries.csv                 → 5 rows
  Loaded: formal-shoes.csv                         → 12 rows
  Loaded: foundation.csv                           → 1 rows
  Loaded: gloves.csv                               → 1 rows
  Loaded: hair-accessory.csv                       → 2 rows
  Loaded: hair-brush-and-comb.csv                  → 1 rows
  Loaded: hair-cream-and-mask.csv                  → 1 rows
  Loaded: hair-masks.csv                           → 1 rows
  Loaded: handbags.csv                             → 18 rows
  Loaded: headphones.csv                           → 3 rows
  Loaded: heels.csv                                → 9 rows
  Loaded: home-fragrance-set.csv                   → 1 rows
  Loaded: innerwear-vests.csv                      → 2 rows
  Loaded: jackets.csv                              → 29 rows
  Loaded: jeans.csv                                → 57 rows
  Loaded: jumpsuit.csv                             → 1 rows
  Loaded: kurta-sets.csv                           → 22 rows
  Loaded: kurtas.csv                               → 20 rows
  Loaded: kurtis.csv                               → 1 rows
  Loaded: lipstick.csv                             → 1 rows
  Loaded: lounge-pants.csv                         → 1 rows
  Loaded: lounge-shorts.csv                        → 1 rows
  Loaded: lounge-tshirts.csv                       → 3 rows
  Loaded: mangalsutra.csv                          → 1 rows
  Loaded: mobile-accessories.csv                   → 1 rows
  Loaded: night-suits.csv                          → 3 rows
  Loaded: nightdress.csv                           → 4 rows
  Loaded: outdoor-masks.csv                        → 2 rows
  Loaded: palazzos.csv                             → 12 rows
  Loaded: perfume-and-body-mist.csv                → 1 rows
  Loaded: pillow-covers.csv                        → 1 rows
  Loaded: ring.csv                                 → 3 rows
  Loaded: runners.csv                              → 3 rows
  Loaded: sandals.csv                              → 6 rows
  Loaded: saree-blouse.csv                         → 2 rows
  Loaded: sarees.csv                               → 22 rows
  Loaded: scarves.csv                              → 2 rows
  Loaded: shampoo-and-conditioner.csv              → 3 rows
  Loaded: shaving-essentials.csv                   → 1 rows
  Loaded: sherwani.csv                             → 5 rows
  Loaded: shirts.csv                               → 97 rows
  Loaded: shorts.csv                               → 21 rows
  Loaded: showpieces.csv                           → 1 rows
  Loaded: skirts.csv                               → 6 rows
  Loaded: sports-shoes.csv                         → 51 rows
  Loaded: sunglasses.csv                           → 1 rows
  Loaded: sweaters.csv                             → 34 rows
  Loaded: sweatshirts.csv                          → 20 rows
  Loaded: swim-tops.csv                            → 1 rows
  Loaded: table-covers.csv                         → 1 rows
  Loaded: thermal-bottoms.csv                      → 1 rows
  Loaded: tights.csv                               → 1 rows
  Loaded: tops.csv                                 → 122 rows
  Loaded: towel-set.csv                            → 1 rows
  Loaded: track-pants.csv                          → 9 rows
  Loaded: trolley-bag.csv                          → 1 rows
  Loaded: trousers.csv                             → 6 rows
  Loaded: trunk.csv                                → 6 rows
  Loaded: tshirts.csv                              → 39 rows
  Loaded: tunics.csv                               → 4 rows
  Loaded: wall-art.csv                             → 1 rows
  Loaded: wallets.csv                              → 7 rows
  Loaded: watches.csv                              → 15 rows
  Loaded: yoga-mats.csv                            → 1 rows

 Combined shape: 5,000 rows × 25 columns
 Saved: dataset/Combined_dataset.csv

## Step 2 — Explore Data

In [3]:
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category,savings_amount
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995.0,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,NaN
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899.0,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,NaN
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999.0,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,NaN
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675.0,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,NaN
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899.0,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe,NaN

In [4]:
df.tail()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category,savings_amount
4995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890.0,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches,NaN
4996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900.0,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches,NaN
4997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950.0,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches,NaN
4998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295.0,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches,NaN
4999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699.0,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats,NaN

In [5]:
print('Shape :', df.shape)
print('Columns:', df.columns.tolist())

Shape : (5000, 25)
Columns: ['product_id', 'title', 'product_description', 'rating', 'ratings_count', 'initial_price', 'discount', 'final_price', 'currency', 'images', 'delivery_options', 'product_details', 'breadcrumbs', 'product_specifications', 'amount_of_stars', 'what_customers_said', 'seller_name', 'sizes', 'videos', 'seller_information', 'variations', 'best_offer', 'more_offers', 'category', 'savings_amount']

In [6]:
print(df.dtypes)

product_id                  int64
title                         str
product_description           str
rating                    float64
ratings_count               int64
initial_price             float64
discount                  float64
final_price                object
currency                      str
images                        str
delivery_options              str
product_details               str
breadcrumbs                   str
product_specifications        str
amount_of_stars               str
what_customers_said        object
seller_name                object
sizes                         str
videos                     object
seller_information         object
variations                 object
best_offer                    str
more_offers                   str
category                      str
savings_amount            float64
dtype: object

In [7]:
num_cols = ['rating','ratings_count','initial_price','final_price','discount']
num_cols = [c for c in num_cols if c in df.columns]
df[num_cols].describe()

            rating  ratings_count  initial_price     discount
count  5000.000000    5000.000000    5000.000000  4637.000000
mean      3.621500      76.691000    2723.241000    53.634246
std       1.373851     241.017778    2407.733495    17.553122
min       0.000000       0.000000     249.000000     1.000000
25%       3.700000       7.000000    1399.000000    45.000000
50%       4.100000      17.000000    1999.000000    56.000000
75%       4.300000      58.000000    3299.000000    65.000000
max       5.000000    4441.000000   22199.000000    88.000000

In [8]:
print('Rows per category (source file):')
print(df['category'].value_counts().to_string())

Rows per category (source file):
category
Combined_dataset            2000
Combined_dataset_cleaned    2000
tops                         122
dresses                      100
shirts                        97
jeans                         57
sports-shoes                  51
tshirts                       39
earrings                      34
sweaters                      34
jackets                       29
casual-shoes                  23
kurta-sets                    22
sarees                        22
shorts                        21
ethnic-dresses                20
kurtas                        20
sweatshirts                   20
handbags                      18
flip-flops                    15
watches                       15
bra                           13
briefs                        12
flats                         12
formal-shoes                  12
palazzos                      12
bedsheets                     11
dupatta                       11
heels                          9
track-pants                    9
wallets                        7
sandals                        6
skirts                         6
trousers                       6
trunk                          6
floor-mats--dhurries           5
sherwani                       5
backpacks                      4
bracelet                       4
nightdress                     4
tunics                         4
headphones                     3
lounge-tshirts                 3
night-suits                    3
ring                           3
runners                        3
shampoo-and-conditioner        3
bodysuit                       2
boots                          2
camisoles                      2
caps                           2
clothing-set                   2
curtains-and-sheers            2
duffel-bag                     2
face-moisturisers              2
hair-accessory                 2
innerwear-vests                2
outdoor-masks                  2
saree-blouse                   2
scarves                        2
bath-robe                      1
bath-towels                    1
bathroom-accessories           1
belts                          1
boxers                         1
candle-holders                 1
chair-cover                    1
clutches                       1
co-ords                        1
cutlery                        1
dinnerware                     1
dungarees                      1
face-wash-and-cleanser         1
foundation                     1
gloves                         1
hair-brush-and-comb            1
hair-cream-and-mask            1
hair-masks                     1
home-fragrance-set             1
jumpsuit                       1
kurtis                         1
lipstick                       1
lounge-pants                   1
lounge-shorts                  1
mangalsutra                    1
mobile-accessories             1
perfume-and-body-mist          1
pillow-covers                  1
shaving-essentials             1
showpieces                     1
sunglasses                     1
swim-tops                      1
table-covers                   1
thermal-bottoms                1
tights                         1
towel-set                      1
trolley-bag                    1
wall-art                       1
yoga-mats                      1

## Step 3 — Handle Missing Values

In [9]:
print('Missing values per column:')
missing = df.isnull().sum()
print(missing[missing > 0])
print(f'\nTotal missing cells: {df.isnull().sum().sum():,}')

Missing values per column:
discount                363
final_price            2000
what_customers_said    2865
seller_name             903
videos                 3905
seller_information     1505
variations             2810
savings_amount         5000
dtype: int64

Total missing cells: 19,351

In [10]:
# Numeric columns → convert & fill with median
for col in ['rating','ratings_count','initial_price','final_price','discount']:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors='coerce')
        df[col] = df[col].fillna(df[col].median())

# Text columns → fill with 'Unknown'
for col in ['title','seller_name','currency']:
    if col in df.columns:
        df[col] = df[col].fillna('Unknown')

print('Missing after fill:', df.isnull().sum().sum())

Missing after fill: 21085

## Step 4 — Filter Rows & Select Columns

In [11]:
key_cols = ['product_id','title','category','rating','ratings_count',
            'initial_price','final_price','discount','seller_name']
key_cols = [c for c in key_cols if c in df.columns]
df[key_cols].head(10)

,product_id,title,category,rating,ratings_count,initial_price,final_price,discount,seller_name
0,8376765,Lino Perros,backpacks,3.8,15,3995.0,NaN,58.0,Unknown
1,9136281,Tommy Hilfiger,backpacks,4.5,67,2899.0,NaN,35.0,Unknown
2,17633752,Lavie,backpacks,4.4,226,2999.0,NaN,65.0,Unknown
3,1376949,F Gear,backpacks,4.4,1052,1675.0,NaN,52.0,Unknown
4,13939916,MYTRIDENT,bath-robe,4.7,12,2899.0,NaN,17.0,Unknown
5,19851824,AVI Living,bath-towels,4.0,5,1399.0,NaN,65.0,Unknown
6,17198778,H&M,bathroom-accessories,4.5,42,1399.0,NaN,56.0,H &███Hen███ & █████████eta█████████████████████
7,18602872,My Room,bedsheets,4.7,10,2999.0,NaN,54.0,Unknown
8,18602850,My Room,bedsheets,4.5,22,2999.0,NaN,54.0,Unknown
9,8961147,Story@home,bedsheets,3.7,7,2199.0,NaN,53.0,Unknown

In [12]:
high_rated = df[df['rating'] >= 4.0]
print(f'High-rated products (>=4.0): {len(high_rated):,}')
high_rated[['title','category','rating','final_price']].head()

High-rated products (>=4.0): 3,075

            title     category  rating  final_price
1  Tommy Hilfiger    backpacks     4.5          NaN
2           Lavie    backpacks     4.4          NaN
3          F Gear    backpacks     4.4          NaN
4       MYTRIDENT    bath-robe     4.7          NaN
5      AVI Living  bath-towels     4.0          NaN

In [13]:
discounted = df[df['discount'] > 0]
print(f'Discounted products: {len(discounted):,}')
discounted[['title','category','initial_price','discount','final_price']].head()

Discounted products: 5,000

            title   category  initial_price  discount  final_price
0     Lino Perros  backpacks         3995.0      58.0          NaN
1  Tommy Hilfiger  backpacks         2899.0      35.0          NaN
2           Lavie  backpacks         2999.0      65.0          NaN
3          F Gear  backpacks         1675.0      52.0          NaN
4       MYTRIDENT  bath-robe         2899.0      17.0          NaN

In [14]:
best_deals = df[(df['rating'] >= 4.0) & (df['discount'] > 0)]
print(f'Best deals (rating>=4 & discounted): {len(best_deals):,}')
best_deals[['title','category','rating','discount','final_price']].head(10)

Best deals (rating>=4 & discounted): 3,075

             title              category  rating  discount  final_price
1   Tommy Hilfiger             backpacks     4.5      35.0          NaN
2            Lavie             backpacks     4.4      65.0          NaN
3           F Gear             backpacks     4.4      52.0          NaN
4        MYTRIDENT             bath-robe     4.7      17.0          NaN
5       AVI Living           bath-towels     4.0      65.0          NaN
6              H&M  bathroom-accessories     4.5      56.0          NaN
7          My Room             bedsheets     4.7      54.0          NaN
8          My Room             bedsheets     4.5      54.0          NaN
10       MYTRIDENT             bedsheets     4.4      46.0          NaN
15    Home Ecstasy             bedsheets     4.5      42.0          NaN

## Step 5 — Remove Duplicates

In [15]:
print('Rows before:', f'{len(df):,}')
print('Duplicate rows:', f'{df.duplicated().sum():,}')
df = df.drop_duplicates()
print('Rows after :', f'{len(df):,}')

Rows before: 5,000
Duplicate rows: 2,000
Rows after : 3,000

## Step 6 — Create Derived Column: `savings_amount`

In [16]:
df['savings_amount'] = (df['initial_price'] - df['final_price']).clip(lower=0).round(2)
df[['title','category','initial_price','final_price','discount','savings_amount']].head(10)

,title,category,initial_price,final_price,discount,savings_amount
0,Lino Perros,backpacks,3995.0,NaN,58.0,NaN
1,Tommy Hilfiger,backpacks,2899.0,NaN,35.0,NaN
2,Lavie,backpacks,2999.0,NaN,65.0,NaN
3,F Gear,backpacks,1675.0,NaN,52.0,NaN
4,MYTRIDENT,bath-robe,2899.0,NaN,17.0,NaN
5,AVI Living,bath-towels,1399.0,NaN,65.0,NaN
6,H&M,bathroom-accessories,1399.0,NaN,56.0,NaN
7,My Room,bedsheets,2999.0,NaN,54.0,NaN
8,My Room,bedsheets,2999.0,NaN,54.0,NaN
9,Story@home,bedsheets,2199.0,NaN,53.0,NaN

In [17]:
print('Top 10 products by savings:')
df.nlargest(10, 'savings_amount')[['title','category','initial_price','final_price','savings_amount']]

Top 10 products by savings:

,title,category,initial_price,final_price,savings_amount
0,Lino Perros,backpacks,3995.0,NaN,NaN
1,Tommy Hilfiger,backpacks,2899.0,NaN,NaN
2,Lavie,backpacks,2999.0,NaN,NaN
3,F Gear,backpacks,1675.0,NaN,NaN
4,MYTRIDENT,bath-robe,2899.0,NaN,NaN
5,AVI Living,bath-towels,1399.0,NaN,NaN
6,H&M,bathroom-accessories,1399.0,NaN,NaN
7,My Room,bedsheets,2999.0,NaN,NaN
8,My Room,bedsheets,2999.0,NaN,NaN
9,Story@home,bedsheets,2199.0,NaN,NaN

In [18]:
print('Average savings by category:')
df.groupby('category')['savings_amount'].mean().sort_values(ascending=False).head(15)

Average savings by category:

category
Combined_dataset           NaN
Combined_dataset_cleaned   NaN
backpacks                  NaN
bath-robe                  NaN
bath-towels                NaN
bathroom-accessories       NaN
bedsheets                  NaN
belts                      NaN
bodysuit                   NaN
boots                      NaN
boxers                     NaN
bra                        NaN
bracelet                   NaN
briefs                     NaN
camisoles                  NaN
Name: savings_amount, dtype: float64

In [19]:
print('Average rating by category:')
df.groupby('category')['rating'].mean().sort_values(ascending=False).head(15)

Average rating by category:

category
cutlery                   5.000000
shaving-essentials        4.900000
face-wash-and-cleanser    4.800000
chair-cover               4.700000
bath-robe                 4.700000
track-pants               4.566667
boxers                    4.500000
hair-cream-and-mask       4.500000
gloves                    4.500000
bathroom-accessories      4.500000
lounge-shorts             4.500000
home-fragrance-set        4.500000
jumpsuit                  4.500000
swim-tops                 4.500000
scarves                   4.500000
Name: rating, dtype: float64

## Step 7 — Save Cleaned Dataset

In [20]:
df.to_csv('dataset/Combined_dataset_cleaned.csv', index=False)
print(' Saved: dataset/Combined_dataset_cleaned.csv')
print(f'Final shape: {df.shape[0]:,} rows × {df.shape[1]} columns')
df.head()

 Saved: dataset/Combined_dataset_cleaned.csv
Final shape: 3,000 rows × 25 columns

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category,savings_amount
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995.0,58.0,NaN,INR,http://assets.myntassets.com/assets/images/837...,...,NaN,Unknown,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,NaN
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899.0,35.0,NaN,INR,http://assets.myntassets.com/assets/images/913...,...,NaN,Unknown,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,NaN
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999.0,65.0,NaN,INR,http://assets.myntassets.com/assets/images/176...,...,NaN,Unknown,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,NaN
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675.0,52.0,NaN,INR,http://assets.myntassets.com/assets/images/137...,...,NaN,Unknown,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,NaN
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899.0,17.0,NaN,INR,http://assets.myntassets.com/assets/images/pro...,...,NaN,Unknown,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe,NaN